Repository ably/ably-java, pull requests merged in 2020-10, with the labels that each got.

#619 Make Ably version more robust
  lib/src/main/java/io/ably/lib/transport/Defaults.java
Labels: enhancement

#617 Remove unnecessary calls to the toString method
  lib/src/main/java/io/ably/lib/transport/WebSocketTransport.java
  lib/src/main/java/io/ably/lib/types/ErrorInfo.java
  lib/src/test/java/io/ably/lib/test/common/Helpers.java
  lib/src/test/java/io/ably/lib/test/realtime/RealtimeChannelHistoryTest.java
  lib/src/test/java/io/ably/lib/test/realtime/RealtimePresenceTest.java
  lib/src/test/java/io/ably/lib/test/rest/RestChannelHistoryTest.java
  lib/src/test/java/io/ably/lib/test/rest/RestErrorTest.java
  lib/src/test/java/io/ably/lib/test/util/TimeHandler.java
Labels: code-quality, enhancement

#622 Fix param and return javadoc statements
  android/src/main/java/io/ably/lib/rest/AblyRest.java
  lib/src/main/java/io/ably/lib/http/AsyncPaginatedQuery.java
  lib/src/main/java/io/ably/lib/http/BasePaginatedQuery.java
  lib/src/main/java/io/ably/lib/http/PaginatedQuery.java
  lib/src/main/java/io/ably/lib/realtime/AblyRealtime.java
  lib/src/main/java/io/ably/lib/realtime/ChannelBase.java
  lib/src/main/java/io/ably/lib/realtime/CompletionListener.java
  lib/src/main/java/io/ably/lib/realtime/Connection.java
  lib/src/main/java/io/ably/lib/realtime/Presence.java
  lib/src/main/java/io/ably/lib/rest/AblyBase.java
  lib/src/main/java/io/ably/lib/rest/Auth.java
  lib/src/main/java/io/ably/lib/rest/ChannelBase.java
  lib/src/main/java/io/ably/lib/types/AsyncHttpPaginatedResponse.java
  lib/src/main/java/io/ably/lib/types/Callback.java
  lib/src/main/java/io/ably/lib/types/Capability.java
  lib/src/main/java/io/ably/lib/types/ClientOptions.java
Labels: documentation

#625 Adopt more Groovy conventions in Gradle scripts
  android/build.gradle
  android/maven.gradle
  build.gradle
  common.gradle
  gradle-lint/src/main/groovy/build-script-rules.groovy
  java/build.gradle
  java/maven.gradle
Labels: build
