Repository ably/ably-java, pull requests merged in 2021-01, with the labels that each got.

#641 Fix/doc 233 update readme
  README.md
Labels: docs

#607 Fix Member Presence
  lib/src/main/java/io/ably/lib/realtime/Presence.java
  lib/src/test/java/io/ably/lib/test/realtime/RealtimePresenceTest.java
Labels: bug

#643 Add workflows
  .github/workflows/assemble.yml
  .github/workflows/check.yml
  .github/workflows/integration-test.yml
  .travis.yml
  ci/run-android-tests.sh
  ci/run-java-tests.sh
  ci/run-tests.sh
  settings.gradle
Labels: CI specific
