Repository ably/ably-java, pull requests merged in 2022-07, with the labels that each got.

#816 Add new renew async method
  lib/src/main/java/io/ably/lib/realtime/AblyRealtime.java
  lib/src/main/java/io/ably/lib/rest/AblyBase.java
  lib/src/main/java/io/ably/lib/rest/Auth.java
  lib/src/main/java/io/ably/lib/transport/ConnectionManager.java
  lib/src/test/java/io/ably/lib/test/realtime/RealtimeAuthTest.java
Labels: enhancement

#820 Update onChannelStateChanged readme with current implementation
  README.md
Labels: documentation

#818 Document thread policy for callbacks and add missing documentation for callbacks
  README.md
  lib/src/main/java/io/ably/lib/realtime/ChannelBase.java
  lib/src/main/java/io/ably/lib/realtime/ChannelStateListener.java
  lib/src/main/java/io/ably/lib/realtime/CompletionListener.java
  lib/src/main/java/io/ably/lib/realtime/ConnectionStateListener.java
  lib/src/main/java/io/ably/lib/realtime/Presence.java
  lib/src/main/java/io/ably/lib/rest/Auth.java
  lib/src/main/java/io/ably/lib/rest/ChannelBase.java
  lib/src/main/java/io/ably/lib/util/EventEmitter.java
Labels: documentation

#822 Increase minSdkVersion to 21 (lollipop)
  README.md
  android/build.gradle
Labels: enhancement

#825 call waiter.close() after breaking from while loop
  lib/src/main/java/io/ably/lib/transport/ConnectionManager.java
  lib/src/test/java/io/ably/lib/test/realtime/RealtimeAuthTest.java
Labels: bug
